metrics:
  configs:
    - name: agent-web
      scrape_configs:
        - job_name: rethinkdb
          static_configs:
            - targets: ['isard-stats-rethinkdb:9055']
              labels:
                domain: ${DOMAIN}
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              target_label: __name__
              replacement: rethinkdb_$1
        - job_name: haproxy-portal
          static_configs:
            - targets: ['isard-portal:9090']
              labels:
                domain: ${DOMAIN}
      remote_write:
        - url: ${PROMETHEUS_ADDRESS}/api/v1/write
