version: '3.5'
services:
  isard-api:
    container_name: isard-api
    #image: isard/webapp:${TAG:-latest}
    ports:
      - "7039:7039"
      - "5000:5000"
    volumes:
    - ${BUILD_ROOT_PATH}/api/src:/api
    - ${BUILD_ROOT_PATH}/component/_common/src:/opt/isardvdi/isardvdi_common
    - ${BUILD_ROOT_PATH}/pkg/gen/proto/python:/opt/isardvdi/isardvdi_protobuf
    # - ${BUILD_ROOT_PATH}/webapp/webapp/lib:/api/lib:ro
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: api/docker/Dockerfile
      target: production
