version: '3.5'
services:
  isard-stats-rethinkdb:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/db/Dockerfile.stats
      args:
        - GOLANG_BUILD_IMAGE
        - GOLANG_RUN_IMAGE
