version: '3.5'
services:
  isard-orchestrator:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: orchestrator/build/package/Dockerfile
      args:
        - "GOLANG_BUILD_IMAGE=${GOLANG_BUILD_IMAGE}"
        - "GOLANG_RUN_IMAGE=${GOLANG_RUN_IMAGE}"
