version: "3.5"
services:
  isard-orchestrator:
    image: ${GOLANG_BUILD_IMAGE}
    command:
      - ash
      - -c
      - >-
        go install github.com/githubnemo/CompileDaemon@latest &&
        go install github.com/go-delve/delve/cmd/dlv@latest &&

        CompileDaemon \
          -log-prefix=false \
          -graceful-kill=true \
          -directory=/orchestrator \
          -build="go build -o /bin/orchestrator ./orchestrator/cmd/orchestrator/main.go" \
          -command="dlv exec --headless=true --listen=:4000 --api-version=2 --accept-multiclient --continue /bin/orchestrator"
    volumes:
      - ${BUILD_ROOT_PATH}/go.mod:/orchestrator/go.mod
      - ${BUILD_ROOT_PATH}/go.sum:/orchestrator/go.sum
      - ${BUILD_ROOT_PATH}/pkg:/orchestrator/pkg
      - ${BUILD_ROOT_PATH}/orchestrator:/orchestrator/orchestrator
      - /tmp/isardvdi-go-devel/cache:/root/.cache/go-build
      - /tmp/isardvdi-go-devel/pkg:/go/pkg
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
