version: '3.5'
services:
  isard-nc-app:
    volumes:
      - ${BUILD_ROOT_PATH}/docker/nextcloud/init.sh:/init.sh:rw
      - ${BUILD_ROOT_PATH}/docker/nextcloud/src:/src:rw
      - ${BUILD_ROOT_PATH}/component/_common/src:/src/_common:rw
  isard-nc-nginx:
    ports:
      - 8081:80
    volumes:
      - ${BUILD_ROOT_PATH}/docker/nextcloud/nginx.conf:/etc/nginx/nginx.conf:rw
      - /opt/isard/nextcloud/html:/var/www/html/isard-nc:rw