version: '3.5'
services:
  isard-portal:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/portal/Dockerfile
      target: production
      args:
        - "HAPROXY_RUN_IMAGE=${HAPROXY_RUN_IMAGE}"
