version: '3.5'
services:
  isard-scheduler:
    container_name: isard-scheduler
    ports:
      - "5001:5000"
    volumes:
    - ${BUILD_ROOT_PATH}/scheduler/src:/src
    - ${BUILD_ROOT_PATH}/component/_common/src:/src/scheduler/_common
