version: "3.5"
services:
  isard-stats-go:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: stats/build/package/Dockerfile
      args:
        - GOLANG_BUILD_IMAGE
        - GOLANG_RUN_IMAGE
