version: '3.5'
services:
  isard-storage:
    volumes:
    - ${BUILD_ROOT_PATH}/docker/storage/api:/api
    - ${BUILD_ROOT_PATH}/component/_common/src:/api/api/_common
    - ${BUILD_ROOT_PATH}/pkg/gen/proto/python:/opt/isardvdi/isardvdi_protobuf
    - ${BUILD_ROOT_PATH}/docker/storage/task:/opt/isardvdi/isardvdi_task
