version: '3.5'
services:
  isard-toolbox:
    container_name: isard-toolbox
    image: ${DOCKER_IMAGE_PREFIX}toolbox:${DOCKER_IMAGE_TAG-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.21
    volumes:
      #- /opt/isard-local/sockets/:/var/run/libvirt/
      - /opt/isard-local/logs:/isard/logs:rw
      - /opt/isard/templates:/isard/templates:rw
      - /opt/isard/groups:/isard/groups:rw
      - /opt/isard/backups:/isard/backups:ro
      - /opt/isard/toolbox/src:/toolbox:rw
      - /opt/isard/media:/isard/media:rw
      # FILEBROWSER VOLUMES
      - ${BUILD_ROOT_PATH}/frontend/src/assets/logo.svg:/branding/img/logo.svg:ro
      - /opt/isard-local/filebrowser:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - FB_BASEURL=/storage
      - WEBAPP_ADMIN_PWD=${WEBAPP_ADMIN_PWD}
      - API_HYPERVISORS_SECRET=${API_HYPERVISORS_SECRET}
