id:
  type: string
  empty: false
  default_setter: genuuid
  coerce: sanitize
name:
  required: true
  type: string
  empty: false
  coerce: sanitize
description:
  required: false
  type: string
  default: ""
  coerce: sanitize
template_id:
  required: true
  type: string
  empty: false
  coerce: sanitize
visible:
  required: false
  type: boolean
  default: false
desktop_name:
  required: false
  type: string
  empty: false
  default: setdeploymentname
  coerce: sanitize
allowed:
  schema: allowed
hardware:
  schema: hardware_update
guest_properties:
  type: dict
  schema: guest_properties_update
image:
  schema: image_update